// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pabeda_Odev.Model;

namespace Pabeda_Odev.Migrations
{
    [DbContext(typeof(DB_Context))]
    [Migration("20191110140547_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pabeda_Odev.Model.Ogrenci", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OkulID")
                        .HasColumnType("int");

                    b.Property<string>("Soyisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TCKimlikNo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OkulID");

                    b.ToTable("Ogrenci");
                });

            modelBuilder.Entity("Pabeda_Odev.Model.OgrenciOgretmen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OgrenciID")
                        .HasColumnType("int");

                    b.Property<int>("OgretmenID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OgrenciID");

                    b.HasIndex("OgretmenID");

                    b.ToTable("OgrenciOgretmen");
                });

            modelBuilder.Entity("Pabeda_Odev.Model.Ogretmen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TCKimlikNo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Ogretmen");
                });

            modelBuilder.Entity("Pabeda_Odev.Model.OgretmenOkul", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OgretmenID")
                        .HasColumnType("int");

                    b.Property<int>("OkulID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OgretmenID");

                    b.HasIndex("OkulID");

                    b.ToTable("OgretmenOkul");
                });

            modelBuilder.Entity("Pabeda_Odev.Model.Okul", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sehir")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Okul");
                });

            modelBuilder.Entity("Pabeda_Odev.Model.Ogrenci", b =>
                {
                    b.HasOne("Pabeda_Odev.Model.Okul", "Okul")
                        .WithMany("Ogrenci")
                        .HasForeignKey("OkulID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pabeda_Odev.Model.OgrenciOgretmen", b =>
                {
                    b.HasOne("Pabeda_Odev.Model.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciOgretmen")
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pabeda_Odev.Model.Ogretmen", "Ogretmen")
                        .WithMany("OgrenciOgretmen")
                        .HasForeignKey("OgretmenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pabeda_Odev.Model.OgretmenOkul", b =>
                {
                    b.HasOne("Pabeda_Odev.Model.Ogretmen", "Ogretmen")
                        .WithMany("OgretmenOkul")
                        .HasForeignKey("OgretmenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pabeda_Odev.Model.Okul", "Okul")
                        .WithMany("OgretmenOkul")
                        .HasForeignKey("OkulID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
